language: php

php:
- 7.0
- 7.1
- 7.2

# cache vendor dirs
cache:
  directories:
  - $HOME/.composer/cache

install:
- travis_retry composer self-update && composer --version
- travis_retry composer update --no-interaction

script:
- vendor/bin/phpunit